namespace WindowsFormsAero.Native;

internal enum TreeViewExtendedStyle : uint
{
	TVS_EX_NOSINGLECOLLAPSE = 1u,
	TVS_EX_MULTISELECT = 2u,
	TVS_EX_DOUBLEBUFFER = 4u,
	TVS_EX_NOINDENTSTATE = 8u,
	TVS_EX_RICHTOOLTIP = 0x10u,
	TVS_EX_AUTOHSCROLL = 0x20u,
	TVS_EX_FADEINOUTEXPANDOS = 0x40u,
	TVS_EX_PARTIALCHECKBOXES = 0x80u,
	TVS_EX_EXCLUSIONCHECKBOXES = 0x100u,
	TVS_EX_DIMMEDCHECKBOXES = 0x200u,
	TVS_EX_DRAWIMAGEASYNC = 0x400u
}
